#!/usr/bin/env python3

import os
from os.path import join
import shlex
import sys

from common import *

source_port = os.getenv("SOURCE_PORT")
assert source_port != "", "SOURCE_PORT environment variable not set."
lmp_file, out_file = sys.argv[1:]
cfg = read_config(lmp_file)

args = [
    source_port, "-iwad", cfg["iwad"],
    "-statdump", out_file,
    "-timedemo", lmp_file,
] + shlex.split(os.getenv("DOOMOPTS", ""))

if "gameversion" in cfg:
    args.extend(("-gameversion", cfg["gameversion"]))

if "pwad" in cfg:
    args.extend(("-file", join("extract", cfg["pwad"])))

print(shlex.join(args))
sys.stdout.close()
os.spawnvp(os.P_WAIT, args[0], args)
