name: Continuous Integration

on:
  push:
    branches:
      - "master"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "master"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: Statcheck test
    runs-on: ubuntu-latest

    steps:
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make chocolate-doom python3 python3-yaml

      - name: Override demos list
        run: |
          echo demos/pwads/av/fast/af253503.zip/af253503.lmp \
               demos/pwads/hr/movie/11hr7159.zip/11hr7159.lmp \
               demos/pwads/mm/movie/30mm8356.zip/30mm8356.lmp \
               demos/pwads/mm2/max/m2221807.zip/m2221807.lmp \
               demos/pwads/requiem/movie/6039rq01.zip/6039rq01.lmp \
             > demos.txt

      - name: Test
        run: |
          make check
