name: Continuous Integration

on:
  push:
    branches:
      - "trunk"
    tags:
      - "*"
    paths-ignore:
      - "**.md"
  pull_request:
    branches:
      - "trunk"
    paths-ignore:
      - "**.md"
  workflow_dispatch:

jobs:
  build:
    name: Statcheck test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install make chocolate-doom python3 python3-yaml

      - name: Override demos list
        run: |
          echo pwads/av/fast/af253503.zip/af253503.lmp \
               pwads/hr/movie/11hr7159.zip/11hr7159.lmp \
               pwads/mm/movie/30mm8356.zip/30mm8356.lmp \
               pwads/mm2/max/m2221807.zip/m2221807.lmp \
               pwads/requiem/movie/6039rq01.zip/6039rq01.lmp \
             > demos.txt

      - name: Build
        run: |
          make output
